import type { ChannelConnection, InboxItem, QuickReply } from "@/lib/types";

export const channels: ChannelConnection[] = [
  {
    id: "fb-crumbtrack",
    network: "facebook",
    name: "CrumbTrack Page",
    handle: "@crumbtrack",
    status: "demo",
    scopes: [
      "pages_show_list",
      "pages_read_engagement",
      "pages_manage_engagement",
      "pages_messaging",
    ],
    lastSync: "Hace 2 min",
  },
  {
    id: "ig-crumbtrack",
    network: "instagram",
    name: "CrumbTrack IG",
    handle: "@crumbtrack.app",
    status: "demo",
    scopes: [
      "instagram_basic",
      "instagram_manage_comments",
      "instagram_manage_messages",
    ],
    lastSync: "Hace 4 min",
  },
];

export const inboxItems: InboxItem[] = [
  {
    id: "item-1001",
    accountId: "ig-crumbtrack",
    network: "instagram",
    source: "ad_comment",
    status: "new",
    sentiment: "hot",
    accountName: "CrumbTrack IG",
    contactName: "Valeria Gomez",
    contactHandle: "@valegomez",
    avatarInitials: "VG",
    title: "Comentario en anuncio: Demo para agencias",
    preview: "Cuanto sale para manejar dos cuentas? Necesito algo simple.",
    receivedAt: "10:42",
    assignee: "Sin asignar",
    campaign: "Lead Ads Julio",
    postTitle: "Demo para agencias",
    unreadCount: 2,
    liked: false,
    hidden: false,
    blocked: false,
    messages: [
      {
        id: "msg-1",
        author: "contact",
        body: "Cuanto sale para manejar dos cuentas? Necesito algo simple.",
        sentAt: "10:42",
      },
      {
        id: "msg-2",
        author: "contact",
        body: "Tambien reciben comentarios de anuncios?",
        sentAt: "10:43",
      },
    ],
  },
  {
    id: "item-1002",
    accountId: "fb-crumbtrack",
    network: "facebook",
    source: "messenger",
    status: "open",
    sentiment: "support",
    accountName: "CrumbTrack Page",
    contactName: "Martin Ruiz",
    contactHandle: "facebook.com/martin.ruiz",
    avatarInitials: "MR",
    title: "Mensaje privado",
    preview: "Tengo un problema conectando la pagina de Facebook.",
    receivedAt: "09:18",
    assignee: "Mauro",
    unreadCount: 1,
    liked: false,
    hidden: false,
    blocked: false,
    messages: [
      {
        id: "msg-3",
        author: "contact",
        body: "Tengo un problema conectando la pagina de Facebook.",
        sentAt: "09:18",
      },
      {
        id: "msg-4",
        author: "agent",
        body: "Pasame el nombre de la pagina y reviso los permisos.",
        sentAt: "09:21",
      },
      {
        id: "msg-5",
        author: "contact",
        body: "Es la pagina principal, me aparece pendiente de permisos.",
        sentAt: "09:25",
      },
    ],
  },
  {
    id: "item-1003",
    accountId: "ig-crumbtrack",
    network: "instagram",
    source: "instagram_dm",
    status: "responded",
    sentiment: "neutral",
    accountName: "CrumbTrack IG",
    contactName: "Nadia Torres",
    contactHandle: "@nadiatorres",
    avatarInitials: "NT",
    title: "DM de Instagram",
    preview: "Gracias, me sirve. Lo pruebo esta tarde.",
    receivedAt: "Ayer",
    assignee: "Mauro",
    unreadCount: 0,
    liked: true,
    hidden: false,
    blocked: false,
    messages: [
      {
        id: "msg-6",
        author: "contact",
        body: "Me mandas mas info del inbox unificado?",
        sentAt: "Ayer 16:02",
      },
      {
        id: "msg-7",
        author: "agent",
        body: "Si. Te permite responder DMs, mensajes de Facebook y comentarios desde una sola bandeja.",
        sentAt: "Ayer 16:08",
      },
      {
        id: "msg-8",
        author: "contact",
        body: "Gracias, me sirve. Lo pruebo esta tarde.",
        sentAt: "Ayer 16:12",
      },
    ],
  },
  {
    id: "item-1004",
    accountId: "fb-crumbtrack",
    network: "facebook",
    source: "post_comment",
    status: "new",
    sentiment: "hot",
    accountName: "CrumbTrack Page",
    contactName: "Cuenta Spam",
    contactHandle: "facebook.com/spam",
    avatarInitials: "CS",
    title: "Comentario en publicacion organica",
    preview: "Promocion falsa, entren al link...",
    receivedAt: "08:51",
    assignee: "Sin asignar",
    postTitle: "Como centralizar mensajes",
    unreadCount: 1,
    liked: false,
    hidden: true,
    blocked: false,
    messages: [
      {
        id: "msg-9",
        author: "contact",
        body: "Promocion falsa, entren al link...",
        sentAt: "08:51",
      },
    ],
  },
];

export const quickReplies: QuickReply[] = [
  {
    id: "qr-1",
    title: "Precio inicial",
    category: "Ventas",
    body: "Hola! Te paso la informacion. La idea es centralizar comentarios, DMs y mensajes en una sola bandeja. Para recomendarte el plan correcto, cuantas cuentas queres conectar?",
    tags: ["precio", "lead"],
  },
  {
    id: "qr-2",
    title: "Permisos de cuenta",
    category: "Soporte",
    body: "Necesitamos que la cuenta sea administradora de la pagina y que el Instagram este conectado como cuenta profesional. Si queres, revisamos los permisos paso a paso.",
    tags: ["permisos", "conexion"],
  },
  {
    id: "qr-3",
    title: "Comentario toxico",
    category: "Moderacion",
    body: "Gracias por avisar. Ya revisamos el comentario y tomamos la accion de moderacion correspondiente.",
    tags: ["moderacion", "ocultar"],
  },
];
